import { Component, Output, EventEmitter } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { CreateNeedPopupComponent } from '../create-need-popup/create-need-popup.component';
import { NeedService } from '../need.service';
import { Need } from '../need';

@Component({
  selector: 'app-create-button',
  templateUrl: './create-button.component.html',
  styleUrl: './create-button.component.css'
})
export class CreateButtonComponent {
  
  constructor(private dialog: MatDialog, private needService: NeedService){}

  @Output() onCreate = new EventEmitter<Need>();

  openDialog(): void{
    const dialogRef = this.dialog.open(CreateNeedPopupComponent, {
      width: '250px'
    });

    dialogRef.afterClosed().subscribe(result => {
      if(result){
        this.submitNeed(result);
      }
    });
  }

  submitNeed(data: any){
    const need: Need = {
      id: -99, // Assuming id is auto-generated by the backend
      name: data.name,
      cost: data.cost,
      quantity: data.quantity,
      type: data.type // Assuming this is already of type needType
    };

    this.needService.addNeed(need).subscribe({
      next: (response) => {
        console.log('Need submitted successfully', response);
        this.onCreate.emit(need);
      },
      error: (error) => {
        console.error('Error submitting need', error);
      }
    });
  }
  
}
